
package com.ocp.day18;

public class LottoJFrame extends javax.swing.JFrame {

    public LottoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lotto_box = new javax.swing.JComboBox<>();
        lotto_button = new javax.swing.JButton();
        lotto_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("樂透電腦選號");

        jLabel1.setFont(new java.awt.Font("新細明體", 0, 36)); // NOI18N
        jLabel1.setText("樂透");

        lotto_box.setFont(new java.awt.Font("新細明體", 0, 36)); // NOI18N
        lotto_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "今彩539", "4星彩" }));
        lotto_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotto_boxActionPerformed(evt);
            }
        });

        lotto_button.setFont(new java.awt.Font("新細明體", 0, 36)); // NOI18N
        lotto_button.setText("選號");
        lotto_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotto_buttonActionPerformed(evt);
            }
        });

        lotto_label.setFont(new java.awt.Font("新細明體", 0, 48)); // NOI18N
        lotto_label.setForeground(new java.awt.Color(0, 0, 255));
        lotto_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotto_label.setText("00,00,00,00,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lotto_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lotto_box, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lotto_button)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lotto_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lotto_button)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(lotto_label)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lotto_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotto_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotto_boxActionPerformed

    private void lotto_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotto_buttonActionPerformed
    int dix = lotto_box.getSelectedIndex();
    // System.out.println(lotto_box.getSelectedIndex());
    //System.out.println(lotto_box.getSelectedItem());
    switch(dix)
    {
        case 0:
    lotto_label.setText(LottoService.get539().toString().replace(',', ' ').replace('[', ' ').replace(']', ' ').trim());
            break;
            case 1:
     lotto_label.setText(LottoService.get4Stars().toString().replace(',', ' ').replace('[', ' ').replace(']', ' ').trim());
            break;
    }    
    }//GEN-LAST:event_lotto_buttonActionPerformed

    public static void main(String args[]) {
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LottoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> lotto_box;
    private javax.swing.JButton lotto_button;
    private javax.swing.JLabel lotto_label;
    // End of variables declaration//GEN-END:variables
}
